CREATE TABLE [dbo].[UserPrivelege]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [RoleId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES UserRole(Id), 
    [Privelege] VARCHAR(MAX) NOT NULL,
)
